name: 'Build LaTex Document'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic resume_cv.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: resume_cv
          path: resume_cv.pdf
